version: '3.1'
services:

  service:
    build:
      context: .
      dockerfile: Dockerfile
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -f -LI -X GET \"localhost:5022/health_check\"" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
    ports:
      - "8080:8080"
    command: ./run_server.sh
